import { useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CalendarDays, Check, CheckCircle2, ChevronRight, Download, MapPin, ShieldCheck, Star, UsersRound } from 'lucide-react';
import apiClient from '../../services/api';
import useGuideApi from '../../hooks/useGuideApi';
import heroImage from "../../assets/LandingPage/mirissa.jpg";

const money = (amount, currency = 'LKR') => new Intl.NumberFormat('en-LK', { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(amount || 0));
const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(value)) : '—';
const dateRange = (item) => `${date(item?.startDate)} – ${date(item?.endDate)}`;
const titleStatus = (value = '') => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const avatar = (name = '') => name.split(/\s+/).map((word) => word[0]).join('').slice(0, 2).toUpperCase() || 'G';

function State({ loading, error, empty, children }) {
  if (loading) return <div className="gs-state" role="status"><span className="gs-spinner" />Loading…</div>;
  if (error) return <div className="gs-state gs-error" role="alert">{error}</div>;
  if (empty) return <div className="gs-state">{empty}</div>;
  return children;
}

export function GuideMarketplace() {
  const { data, loading, error } = useGuideApi('/guides');
  return <section className="gs-page"><div className="gs-page-heading"><div><span className="gs-eyebrow">GUIDE MARKETPLACE</span><h1>Local experts</h1><p>Browse public guide profiles or post a request to receive trip-specific bids.</p></div><Link className="gs-primary" to="/dashboard-Tourist/guides/request">Request a Guide</Link></div><State loading={loading} error={error} empty={!data?.guides?.length && 'No guide profiles are available yet.'}><div className="gs-card-grid">{data?.guides?.map((guide) => <article className="gs-guide-mini" key={guide.user._id}><div className="gs-avatar gs-avatar-lg">{avatar(guide.user.fullName)}</div><div><h2>{guide.user.fullName}</h2><p>{guide.professionalTitle || 'Local Tour Guide'}</p><span><Star size={15} fill="currentColor" /> {Number(guide.ratingAverage || 0).toFixed(1)} ({guide.reviewCount || 0})</span></div><Link to={`/dashboard-Tourist/guides/${guide.user._id}`}>View Profile</Link></article>)}</div></State></section>;
}

export function RequestGuide() {
  const navigate = useNavigate();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ destination: '', startDate: '', endDate: '', travellers: 1, language: 'English', guideTypes: [], budgetMin: 0, budgetMax: '', currency: 'LKR', meetingLocation: '', requirements: '' });
  const update = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  const toggleType = (type) => setForm((value) => ({ ...value, guideTypes: value.guideTypes.includes(type) ? value.guideTypes.filter((item) => item !== type) : [...value.guideTypes, type] }));
  const submit = async (event) => {
    event.preventDefault(); if (submitting) return; setError('');
    if (!form.destination || !form.startDate || !form.endDate || !form.budgetMax) return setError('Please complete all required fields.');
    setSubmitting(true);
    try { const result = await apiClient.post('/guides/requests', form); navigate(`/dashboard-Tourist/guides/requests/${result.requestId}/bids`); }
    catch (err) { setError(err.message); }
    finally { setSubmitting(false); }
  };
  return <section className="gs-request-page"><div className="gs-request-hero"><img src={heroImage} alt="Aerial view of Mirissa beach and palm-lined coast" /><div><h1>Request a Guide</h1><p>Find the perfect local expert for your Sri Lankan adventure.</p></div></div><form className="gs-form-card gs-request-form" onSubmit={submit}><div className="gs-form-grid"><label>Destination *<input name="destination" value={form.destination} onChange={update} placeholder="e.g. Galle and Mirissa" required /></label><div className="gs-field"><span>Travel Dates *</span><div className="gs-date-pair"><input aria-label="Travel start date" type="date" name="startDate" value={form.startDate} onChange={update} required /><input aria-label="Travel end date" type="date" name="endDate" min={form.startDate} value={form.endDate} onChange={update} required /></div></div><label>Number of Travelers *<input type="number" min="1" max="100" name="travellers" value={form.travellers} onChange={update} required /></label><label>Language Preference *<select name="language" value={form.language} onChange={update}><option>English</option><option>Sinhala</option><option>Tamil</option><option>French</option><option>German</option></select></label><fieldset className="gs-full"><legend>Guide Type</legend><div className="gs-choice-row">{['Cultural', 'Adventure', 'City', 'Nature'].map((type) => <label key={type} className={form.guideTypes.includes(type) ? 'selected' : ''}><input type="checkbox" checked={form.guideTypes.includes(type)} onChange={() => toggleType(type)} />{type}</label>)}</div></fieldset><div className="gs-field gs-full"><span>Budget Range (per day) *</span><div className="gs-budget-row"><input aria-label="Minimum daily budget" type="number" min="0" name="budgetMin" value={form.budgetMin} onChange={update} /><span>to</span><input aria-label="Maximum daily budget" type="number" min="0" name="budgetMax" value={form.budgetMax} onChange={update} placeholder="Maximum" required /><select aria-label="Currency" name="currency" value={form.currency} onChange={update}><option>LKR</option><option>USD</option><option>EUR</option></select></div></div><label className="gs-full">Meeting Location<input name="meetingLocation" value={form.meetingLocation} onChange={update} placeholder="Hotel, station, or landmark" /></label><label className="gs-full">Special Requirements<textarea name="requirements" value={form.requirements} onChange={update} rows="5" placeholder="Tell guides about interests, accessibility needs, or timing…" /></label></div>{error && <p className="gs-inline-error" role="alert">{error}</p>}<button className="gs-primary gs-submit-wide" disabled={submitting}>{submitting ? 'Posting request…' : 'Post Guide Request'}</button></form></section>;
}

export function MyGuideRequests() {
  const { data, loading, error } = useGuideApi('/guides/requests');
  return <section className="gs-page"><div className="gs-page-heading"><div><span className="gs-eyebrow">MY TRIPS</span><h1>My Guide Requests</h1><p>Track proposals and bookings created from your requests.</p></div><Link className="gs-primary" to="/dashboard-Tourist/guides/request">New Request</Link></div><State loading={loading} error={error} empty={!data?.requests?.length && 'You have not posted a guide request yet.'}><div className="gs-list">{data?.requests?.map((item) => <article className="gs-request-row" key={item._id}><div className="gs-request-icon"><MapPin /></div><div><h2>{item.destination}</h2><p>{dateRange(item)} · {item.travellers} traveler{item.travellers === 1 ? '' : 's'} · {item.language}</p><small>{item.bidCount} proposal{item.bidCount === 1 ? '' : 's'}</small></div><span className={`gs-status status-${item.status}`}>{titleStatus(item.status)}</span><Link to={`/dashboard-Tourist/guides/requests/${item._id}/bids`}>Open bids <ChevronRight size={16} /></Link></article>)}</div></State></section>;
}

export function AvailableBids() {
  const { requestId } = useParams();
  const { data, loading, error } = useGuideApi(`/guides/requests/${requestId}/bids`);
  return <section className="gs-page"><div className="gs-page-heading"><div><span className="gs-eyebrow">YOUR REQUEST</span><h1>Available Guides</h1><p>Compare real proposals for your trip.</p></div><Link to="/dashboard-Tourist/guides/requests">All requests</Link></div>{data?.request && <div className="gs-trip-summary"><div><MapPin /><span><strong>{data.request.destination}</strong>{dateRange(data.request)}</span></div><div><UsersRound /><span><strong>{data.request.travellers} travelers</strong>{data.request.language}</span></div><div><CalendarDays /><span><strong>{data.bids.length} bids received</strong>{titleStatus(data.request.status)}</span></div></div>}<State loading={loading} error={error} empty={!data?.bids?.length && 'No guide bids have arrived yet. Check back soon.'}><div className="gs-bid-list">{data?.bids?.map((bid) => { const profile = bid.guide.profile || {}; return <article className="gs-bid-card" key={bid._id}><div className="gs-bid-person"><div className="gs-avatar gs-avatar-xl">{avatar(bid.guide.fullName)}</div><div><h2>{bid.guide.fullName} {profile.verified && <ShieldCheck className="gs-verified" size={18} />}</h2><p><Star size={15} fill="currentColor" /> {Number(profile.ratingAverage || 0).toFixed(1)} · {profile.reviewCount || 0} reviews</p><span>{profile.experienceYears || 0} years experience</span></div></div><div className="gs-tags">{(profile.expertise || []).slice(0, 4).map((tag) => <span key={tag}>{tag}</span>)}</div><p className="gs-proposal">{bid.proposal}</p><div className="gs-bid-total"><span>TOTAL BID</span><strong>{money(bid.amount, bid.currency)}</strong></div><div className="gs-bid-actions"><Link to={`/dashboard-Tourist/guides/${bid.guide._id}?requestId=${requestId}&bidId=${bid._id}`}>View Profile</Link><Link className="gs-primary" to={`/dashboard-Tourist/guides/requests/${requestId}/confirm/${bid._id}`}>Select Guide</Link></div></article>; })}</div></State></section>;
}

export function GuideProfile() {
  const { guideId } = useParams(); const [params] = useSearchParams();
  const requestId = params.get('requestId'); const bidId = params.get('bidId');
  const { data, loading, error } = useGuideApi(`/guides/${guideId}`);
  const { data: preview } = useGuideApi(requestId && bidId ? `/guides/requests/${requestId}/bids/${bidId}/confirmation` : null);
  const guide = data?.guide;
  const cta = requestId && bidId ? `/dashboard-Tourist/guides/requests/${requestId}/confirm/${bidId}` : '/dashboard-Tourist/guides/request';
  return <State loading={loading} error={error}><section className="gs-profile-page">{guide && <><div className="gs-profile-cover">{guide.coverImage ? <img src={guide.coverImage} alt="Guide cover" /> : <div className="gs-cover-fallback" />}</div><div className="gs-profile-header"><div className="gs-avatar gs-avatar-profile">{avatar(guide.user.fullName)}</div><div><h1>{guide.user.fullName} {guide.verified && <ShieldCheck className="gs-verified" />}</h1><p><Star fill="currentColor" /> {Number(guide.ratingAverage).toFixed(1)} ({guide.reviewCount} reviews)</p><strong>{guide.professionalTitle}</strong></div></div><div className="gs-profile-grid"><div className="gs-profile-content"><section><h2>About</h2><p>{guide.bio || 'This guide is still completing their public introduction.'}</p></section><section><h2>Languages Spoken</h2><div className="gs-tags">{guide.languages.length ? guide.languages.map((item) => <span key={item}>{item}</span>) : <span>Not specified</span>}</div></section><section><h2>Experience Highlights</h2><ul>{guide.highlights.length ? guide.highlights.map((item) => <li key={item}><Check />{item}</li>) : <li><Check />{guide.experienceYears} years of local guiding experience</li>}</ul></section><section><h2>Tour Gallery</h2><div className="gs-gallery">{guide.gallery.length ? guide.gallery.map((src) => <img src={src} alt="Tour experience" key={src} />) : <div className="gs-gallery-empty">Gallery photos coming soon</div>}</div></section><section><h2>Tourist Reviews</h2>{guide.reviews.length ? guide.reviews.map((review) => <article className="gs-review" key={review._id}><strong>{review.touristName}</strong><span>{'★'.repeat(review.rating)}</span><p>{review.comment}</p></article>) : <p>No reviews yet.</p>}</section></div><aside className="gs-book-card"><span>{preview ? 'Proposal rate' : 'Guide rate'}</span><strong>{money(preview?.bid?.amount || guide.dailyRate, preview?.bid?.currency || guide.currency)} <small>/ day</small></strong><div><Check /> Available on confirmed dates</div><h3>Included services</h3><ul>{(preview?.bid?.includedServices?.length ? preview.bid.includedServices : guide.includedServices).map((item) => <li key={item}><Check />{item}</li>)}</ul>{preview && <><hr /><div className="gs-estimate"><span>Estimated total</span><strong>{money(preview.totals.total, preview.totals.currency)}</strong></div></>}<Link className="gs-primary gs-submit-wide" to={cta}>BOOK THIS GUIDE</Link>{!requestId && <p className="gs-hint">Start a request to receive a date-specific bid from this guide.</p>}</aside></div></>}</section></State>;
}

export function ConfirmBooking() {
  const { requestId, bidId } = useParams(); const navigate = useNavigate();
  const { data, loading, error } = useGuideApi(`/guides/requests/${requestId}/bids/${bidId}/confirmation`);
  const [submitting, setSubmitting] = useState(false); const [submitError, setSubmitError] = useState('');
  const confirm = async () => { if (submitting) return; setSubmitting(true); setSubmitError(''); try { const result = await apiClient.post('/guides/bookings', { requestId, bidId }); navigate(`/dashboard-Tourist/guides/bookings/${result.bookingId}`); } catch (err) { setSubmitError(err.message); } finally { setSubmitting(false); } };
  return <State loading={loading} error={error}><section className="gs-page gs-confirm-page">{data && <><div className="gs-page-heading"><div><span className="gs-eyebrow">FINAL REVIEW</span><h1>Confirm and Pay</h1><p>Please review your trip details and choose a payment method.</p></div></div><div className="gs-confirm-grid"><div><h2><span>1</span> Trip Details</h2><div className="gs-trip-details"><div><span>DATES</span><strong>{dateRange(data.request)}</strong></div><div><span>TRAVELERS</span><strong>{data.request.travellers}</strong></div><div><span>MEETING LOCATION</span><strong>{data.request.meetingLocation || data.request.destination}</strong></div></div><h2><span>2</span> Payment Method</h2><div className="gs-payment-options"><div className="selected"><div><strong>Manual confirmation</strong><p>No payment gateway is connected. Your booking will be created as unpaid.</p></div><CheckCircle2 /></div><details><summary>Credit / Debit Card <span>Unavailable</span></summary><div className="gs-card-fields"><label>Card Number<input disabled placeholder="•••• •••• •••• ••••" /></label><label>Expiry Date<input disabled placeholder="MM / YY" /></label><label>CVV<input disabled placeholder="•••" /></label></div></details><details><summary>PayPal <span>Unavailable</span></summary></details><details><summary>Bank Transfer <span>Unavailable</span></summary></details></div></div><aside className="gs-order-card"><h2>Order Summary</h2><div className="gs-order-guide"><div className="gs-avatar">{avatar(data.guide.fullName)}</div><div><strong>{data.guide.fullName}</strong><span><Star fill="currentColor" /> {Number(data.guide.profile?.ratingAverage || 0).toFixed(1)} ({data.guide.profile?.reviewCount || 0})</span></div></div><dl><div><dt>{money(data.totals.dailyRate, data.totals.currency)} × {data.totals.days} days</dt><dd>{money(data.totals.subtotal, data.totals.currency)}</dd></div><div><dt>Service fee</dt><dd>{money(data.totals.serviceFee, data.totals.currency)}</dd></div><div><dt>Tax / VAT</dt><dd>{money(data.totals.tax, data.totals.currency)}</dd></div><div className="total"><dt>TOTAL</dt><dd>{money(data.totals.total, data.totals.currency)}</dd></div></dl>{submitError && <p className="gs-inline-error" role="alert">{submitError}</p>}<button className="gs-primary gs-submit-wide" disabled={submitting} onClick={confirm}>{submitting ? 'Confirming…' : 'Pay & Confirm Booking'}</button><p className="gs-hint">Payment remains unpaid until a supported payment process is completed.</p></aside></div></>}</section></State>;
}

export function BookingConfirmed() {
  const { bookingId } = useParams(); const { data, loading, error } = useGuideApi(`/guides/bookings/${bookingId}`); const booking = data?.booking;
  const download = () => { if (!booking) return; const receipt = [`SMART VIRTUAL TOURISM GUIDE`, `Booking reference: ${booking.bookingReference}`, `Tourist: ${booking.tourist?.fullName}`, `Guide: ${booking.guide?.fullName}`, `Dates: ${dateRange(booking)}`, `Travelers: ${booking.travellers}`, `Amount: ${money(booking.total, booking.currency)}`, `Booking status: ${titleStatus(booking.status)}`, `Payment status: ${titleStatus(booking.paymentStatus)}`, `Generated: ${new Date().toLocaleString('en-GB')}`].join('\n'); const url = URL.createObjectURL(new Blob([receipt], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `${booking.bookingReference}-slip.txt`; link.click(); URL.revokeObjectURL(url); };
  return <State loading={loading} error={error}><section className="gs-success-page">{booking && <><CheckCircle2 className="gs-success-icon" /><h1>Booking Confirmed</h1><p>Your request with <strong>{booking.guide?.fullName}</strong> has been recorded and is awaiting the guide’s confirmation.</p><div className="gs-booking-details"><h2>Booking Details</h2><dl><div><dt>BOOKING ID</dt><dd>{booking.bookingReference}</dd></div><div><dt>GUIDE NAME</dt><dd>{booking.guide?.fullName}</dd></div><div><dt>DATES</dt><dd>{dateRange(booking)}</dd></div><div><dt>TOTAL</dt><dd>{money(booking.total, booking.currency)}</dd></div><div><dt>BOOKING STATUS</dt><dd><span className={`gs-status status-${booking.status}`}>{titleStatus(booking.status)}</span></dd></div><div><dt>PAYMENT STATE</dt><dd><span className={`gs-status status-${booking.paymentStatus}`}>{titleStatus(booking.paymentStatus)}</span></dd></div></dl><button className="gs-secondary gs-submit-wide" onClick={download}><Download /> Download the Slip</button>{booking.status === 'completed' && !data.review && <Link className="gs-primary gs-submit-wide" to={`/dashboard-Tourist/guides/bookings/${bookingId}/review`}>Review your Guide</Link>}</div></>}</section></State>;
}

export function ReviewBooking() {
  const { bookingId } = useParams(); const navigate = useNavigate(); const { data, loading, error } = useGuideApi(`/guides/bookings/${bookingId}`); const [rating, setRating] = useState(5); const [comment, setComment] = useState(''); const [submitting, setSubmitting] = useState(false); const [submitError, setSubmitError] = useState('');
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setSubmitError(''); try { await apiClient.post(`/guides/bookings/${bookingId}/reviews`, { rating, comment }); navigate(`/dashboard-Tourist/guides/${data.booking.guide._id}`); } catch (err) { setSubmitError(err.message); } finally { setSubmitting(false); } };
  return <State loading={loading} error={error}><section className="gs-page gs-review-page"><div className="gs-form-card"><span className="gs-eyebrow">SHARE YOUR EXPERIENCE</span><h1>Review {data?.booking?.guide?.fullName}</h1>{data?.review ? <p>You have already reviewed this booking.</p> : <form onSubmit={submit}><fieldset><legend>Rating</legend><div className="gs-star-picker">{[1, 2, 3, 4, 5].map((value) => <button type="button" key={value} aria-label={`${value} stars`} onClick={() => setRating(value)} className={value <= rating ? 'selected' : ''}><Star fill="currentColor" /></button>)}</div></fieldset><label>Review / Comment<textarea required minLength="10" rows="6" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="What made this guide experience memorable?" /></label>{submitError && <p className="gs-inline-error">{submitError}</p>}<button className="gs-primary gs-submit-wide" disabled={submitting}>{submitting ? 'Submitting…' : 'Submit Review'}</button></form>}</div></section></State>;
}
