export const CITIES_LIST = [
  // --- Ampara District ---
  { division: "Addalachchenai", district: "Ampara" },
  { division: "Akkaraipattu", district: "Ampara" },
  { division: "Alayadiwembu", district: "Ampara" },
  { division: "Ampara", district: "Ampara" },
  { division: "Damana", district: "Ampara" },
  { division: "Dehiattakandiya", district: "Ampara" },
  { division: "Eragama", district: "Ampara" },
  { division: "Kalmunai", district: "Ampara" },
  { division: "Karativu", district: "Ampara" },
  { division: "Lahugala", district: "Ampara" },
  { division: "Mahaoya", district: "Ampara" },
  { division: "Navithanveli", district: "Ampara" },
  { division: "Ninthavur", district: "Ampara" },
  { division: "Padiyathalawa", district: "Ampara" },
  { division: "Pothuvil", district: "Ampara" },
  { division: "Sainthamarathu", district: "Ampara" },
  { division: "Samanthurai", district: "Ampara" },
  { division: "Thirukkovil", district: "Ampara" },
  { division: "Uhana", district: "Ampara" },

  // --- Anuradhapura District ---
  { division: "Galenbindunuwewa", district: "Anuradhapura" },
  { division: "Galnewa", district: "Anuradhapura" },
  { division: "Horowpothana", district: "Anuradhapura" },
  { division: "Ipalogama", district: "Anuradhapura" },
  { division: "Kahatagasdigiliya", district: "Anuradhapura" },
  { division: "Kebithigollewa", district: "Anuradhapura" },
  { division: "Kekirawa", district: "Anuradhapura" },
  { division: "Maha Vilachchiya", district: "Anuradhapura" },
  { division: "Medawachchiya", district: "Anuradhapura" },
  { division: "Mihinthale", district: "Anuradhapura" },
  { division: "Nachchadoowa", district: "Anuradhapura" },
  { division: "Nochchiyagama", district: "Anuradhapura" },
  { division: "Nuwaragam Palatha Central", district: "Anuradhapura" },
  { division: "Nuwaragam Palatha East", district: "Anuradhapura" },
  { division: "Padaviya", district: "Anuradhapura" },
  { division: "Palagala", district: "Anuradhapura" },
  { division: "Palugaswewa", district: "Anuradhapura" },
  { division: "Rajanganaya", district: "Anuradhapura" },
  { division: "Rambewa", district: "Anuradhapura" },
  { division: "Thalawa", district: "Anuradhapura" },
  { division: "Thambuttegama", district: "Anuradhapura" },
  { division: "Thirappane", district: "Anuradhapura" },

  // --- Badulla District ---
  { division: "Badulla", district: "Badulla" },
  { division: "Bandarawela", district: "Badulla" },
  { division: "Ella", district: "Badulla" },
  { division: "Haldummulla", district: "Badulla" },
  { division: "Hali-Ela", district: "Badulla" },
  { division: "Haputale", district: "Badulla" },
  { division: "Kandaketiya", district: "Badulla" },
  { division: "Lunugala", district: "Badulla" },
  { division: "Mahiyanganaya", district: "Badulla" },
  { division: "Meegahakivula", district: "Badulla" },
  { division: "Passara", district: "Badulla" },
  { division: "Rideemaliyadda", district: "Badulla" },
  { division: "Soranathota", district: "Badulla" },
  { division: "Uva-Paranagama", district: "Badulla" },
  { division: "Welimada", district: "Badulla" },

  // --- Batticaloa District ---
  { division: "Eravur Pattu", district: "Batticaloa" },
  { division: "Eravur Town", district: "Batticaloa" },
  { division: "Kattankudy", district: "Batticaloa" },
  { division: "Koralai Pattu (Valachchenai)", district: "Batticaloa" },
  { division: "Koralai Pattu Central", district: "Batticaloa" },
  { division: "Koralai Pattu North (Vaharai)", district: "Batticaloa" },
  { division: "Koralai Pattu South (Kiran)", district: "Batticaloa" },
  { division: "Koralai Pattu West (Oddamavadi)", district: "Batticaloa" },
  { division: "Manmunai North", district: "Batticaloa" },
  { division: "Manmunai Pattu (Araipattai)", district: "Batticaloa" },
  { division: "Manmunai South & Eruvil Pattu", district: "Batticaloa" },
  { division: "Manmunai South-West", district: "Batticaloa" },
  { division: "Manmunai West", district: "Batticaloa" },
  { division: "Porativu Pattu", district: "Batticaloa" },

  // --- Colombo District ---
  { division: "Colombo", district: "Colombo" },
  { division: "Dehiwala", district: "Colombo" },
  { division: "Homagama", district: "Colombo" },
  { division: "Kaduwela", district: "Colombo" },
  { division: "Kesbewa", district: "Colombo" },
  { division: "Kolonnawa", district: "Colombo" },
  { division: "Maharagama", district: "Colombo" },
  { division: "Moratuwa", district: "Colombo" },
  { division: "Padukka", district: "Colombo" },
  { division: "Ratmalana", district: "Colombo" },
  { division: "Seethawaka", district: "Colombo" },
  { division: "Sri Jayawardenepura Kotte", district: "Colombo" },
  { division: "Thimbirigasyaya", district: "Colombo" },

  // --- Galle District ---
  { division: "Akmeemana", district: "Galle" },
  { division: "Ambalangoda", district: "Galle" },
  { division: "Baddegama", district: "Galle" },
  { division: "Balapitiya", district: "Galle" },
  { division: "Bentota", district: "Galle" },
  { division: "Bope-Poddala", district: "Galle" },
  { division: "Elpitiya", district: "Galle" },
  { division: "Galle Four Gravets", district: "Galle" },
  { division: "Habaraduwa", district: "Galle" },
  { division: "Hikkaduwa", district: "Galle" },
  { division: "Imaduwa", district: "Galle" },
  { division: "Karandeniya", district: "Galle" },
  { division: "Nagoda", district: "Galle" },
  { division: "Neluwa", district: "Galle" },
  { division: "Niyagama", district: "Galle" },
  { division: "Thawalama", district: "Galle" },
  { division: "Welivitiya-Divithura", district: "Galle" },
  { division: "Yakkalamulla", district: "Galle" },

  // --- Gampaha District ---
  { division: "Attanagalla", district: "Gampaha" },
  { division: "Biyagama", district: "Gampaha" },
  { division: "Divulapitiya", district: "Gampaha" },
  { division: "Dompe", district: "Gampaha" },
  { division: "Gampaha", district: "Gampaha" },
  { division: "Ja-Ela", district: "Gampaha" },
  { division: "Katana", district: "Gampaha" },
  { division: "Kelaniya", district: "Gampaha" },
  { division: "Mahara", district: "Gampaha" },
  { division: "Minuwangoda", district: "Gampaha" },
  { division: "Mirigama", district: "Gampaha" },
  { division: "Negombo", district: "Gampaha" },
  { division: "Wattala", district: "Gampaha" },

  // --- Hambantota District ---
  { division: "Ambalanthota", district: "Hambantota" },
  { division: "Angunakolapelessa", district: "Hambantota" },
  { division: "Beliatta", district: "Hambantota" },
  { division: "Hambantota", district: "Hambantota" },
  { division: "Katuwana", district: "Hambantota" },
  { division: "Lunugamvehera", district: "Hambantota" },
  { division: "Okewela", district: "Hambantota" },
  { division: "Sooriyawewa", district: "Hambantota" },
  { division: "Tangalle", district: "Hambantota" },
  { division: "Thissamaharama", district: "Hambantota" },
  { division: "Walasmulla", district: "Hambantota" },
  { division: "Weeraketiya", district: "Hambantota" },

  // --- Jaffna District ---
  { division: "Delft", district: "Jaffna" },
  { division: "Island North (Kayts)", district: "Jaffna" },
  { division: "Island South (Velanai)", district: "Jaffna" },
  { division: "Jaffna", district: "Jaffna" },
  { division: "Karainagar", district: "Jaffna" },
  { division: "Nallur", district: "Jaffna" },
  { division: "Thenmaradchi (Chavakachcheri)", district: "Jaffna" },
  { division: "Vadamaradchi East", district: "Jaffna" },
  { division: "Vadamaradchi North", district: "Jaffna" },
  { division: "Vadamaradchi South-West", district: "Jaffna" },
  { division: "Valikamam East", district: "Jaffna" },
  { division: "Valikamam North", district: "Jaffna" },
  { division: "Valikamam South", district: "Jaffna" },
  { division: "Valikamam South-West", district: "Jaffna" },
  { division: "Valikamam West", district: "Jaffna" },

  // --- Kalutara District ---
  { division: "Agalawatta", district: "Kalutara" },
  { division: "Bandaragama", district: "Kalutara" },
  { division: "Beruwala", district: "Kalutara" },
  { division: "Bulathsinhala", district: "Kalutara" },
  { division: "Dodangoda", district: "Kalutara" },
  { division: "Horana", district: "Kalutara" },
  { division: "Ingiriya", district: "Kalutara" },
  { division: "Kalutara", district: "Kalutara" },
  { division: "Madurawala", district: "Kalutara" },
  { division: "Mathugama", district: "Kalutara" },
  { division: "Millaniya", district: "Kalutara" },
  { division: "Palindanuwara", district: "Kalutara" },
  { division: "Panadura", district: "Kalutara" },
  { division: "Walallawita", district: "Kalutara" },

  // --- Kandy District ---
  { division: "Akurana", district: "Kandy" },
  { division: "Delthota", district: "Kandy" },
  { division: "Doluwa", district: "Kandy" },
  { division: "Ganga Ihala Korale", district: "Kandy" },
  { division: "Harispattuwa", district: "Kandy" },
  { division: "Hatharaliyadda", district: "Kandy" },
  { division: "Kandy Four Gravets", district: "Kandy" },
  { division: "Kundasale", district: "Kandy" },
  { division: "Medadumbara", district: "Kandy" },
  { division: "Minipe", district: "Kandy" },
  { division: "Panvila", district: "Kandy" },
  { division: "Pasbage Korale", district: "Kandy" },
  { division: "Pathadumbara", district: "Kandy" },
  { division: "Pathahewaheta", district: "Kandy" },
  { division: "Poojapitiya", district: "Kandy" },
  { division: "Thumpane", district: "Kandy" },
  { division: "Udadumbara", district: "Kandy" },
  { division: "Udapalatha", district: "Kandy" },
  { division: "Udunuwara", district: "Kandy" },
  { division: "Yatinuwara", district: "Kandy" },

  // --- Kegalle District ---
  { division: "Aranayaka", district: "Kegalle" },
  { division: "Bulathkohupitiya", district: "Kegalle" },
  { division: "Dehiovita", district: "Kegalle" },
  { division: "Deraniyagala", district: "Kegalle" },
  { division: "Galigamuwa", district: "Kegalle" },
  { division: "Kegalle", district: "Kegalle" },
  { division: "Mawanella", district: "Kegalle" },
  { division: "Rambukkana", district: "Kegalle" },
  { division: "Ruwanwella", district: "Kegalle" },
  { division: "Warakapola", district: "Kegalle" },
  { division: "Yatiyanthota", district: "Kegalle" },

  // --- Kilinochchi District ---
  { division: "Kandawali", district: "Kilinochchi" },
  { division: "Karachchi", district: "Kilinochchi" },
  { division: "Pachchilaipalli", district: "Kilinochchi" },
  { division: "Poonakary", district: "Kilinochchi" },

  // --- Kurunegala District ---
  { division: "Alawwa", district: "Kurunegala" },
  { division: "Ambanpola", district: "Kurunegala" },
  { division: "Bamunakotuwa", district: "Kurunegala" },
  { division: "Bingiriya", district: "Kurunegala" },
  { division: "Ehetuwewa", district: "Kurunegala" },
  { division: "Galgamuwa", district: "Kurunegala" },
  { division: "Ganewatta", district: "Kurunegala" },
  { division: "Giribawa", district: "Kurunegala" },
  { division: "Ibbagamuwa", district: "Kurunegala" },
  { division: "Katupotha", district: "Kurunegala" },
  { division: "Kobeigane", district: "Kurunegala" },
  { division: "Kotavehera", district: "Kurunegala" },
  { division: "Kuliyapitiya East", district: "Kurunegala" },
  { division: "Kuliyapitiya West", district: "Kurunegala" },
  { division: "Kurunegala", district: "Kurunegala" },
  { division: "Mahawa", district: "Kurunegala" },
  { division: "Mallawapitiya", district: "Kurunegala" },
  { division: "Maspotha", district: "Kurunegala" },
  { division: "Mawathagama", district: "Kurunegala" },
  { division: "Narammala", district: "Kurunegala" },
  { division: "Nikaweratiya", district: "Kurunegala" },
  { division: "Panduwasnuwara", district: "Kurunegala" },
  { division: "Pannala", district: "Kurunegala" },
  { division: "Polgahawela", district: "Kurunegala" },
  { division: "Polpithigama", district: "Kurunegala" },
  { division: "Rasnayakapura", district: "Kurunegala" },
  { division: "Rideegama", district: "Kurunegala" },
  { division: "Udubaddawa", district: "Kurunegala" },
  { division: "Wariyapola", district: "Kurunegala" },
  { division: "Weerambugedara", district: "Kurunegala" },

  // --- Mannar District ---
  { division: "Madhu", district: "Mannar" },
  { division: "Mannar Town", district: "Mannar" },
  { division: "Manthai West", district: "Mannar" },
  { division: "Musali", district: "Mannar" },
  { division: "Nanaddan", district: "Mannar" },

  // --- Matale District ---
  { division: "Ambanganga Korale", district: "Matale" },
  { division: "Dambulla", district: "Matale" },
  { division: "Galewela", district: "Matale" },
  { division: "Laggala-Pallegama", district: "Matale" },
  { division: "Matale", district: "Matale" },
  { division: "Naula", district: "Matale" },
  { division: "Pallepola", district: "Matale" },
  { division: "Rattota", district: "Matale" },
  { division: "Ukuwela", district: "Matale" },
  { division: "Wilgamuwa", district: "Matale" },
  { division: "Yatawatta", district: "Matale" },

  // --- Matara District ---
  { division: "Akuressa", district: "Matara" },
  { division: "Athuraliya", district: "Matara" },
  { division: "Devinuwara", district: "Matara" },
  { division: "Dickwella", district: "Matara" },
  { division: "Hakmana", district: "Matara" },
  { division: "Kamburupitiya", district: "Matara" },
  { division: "Kirinda-Puhulwella", district: "Matara" },
  { division: "Kotapola", district: "Matara" },
  { division: "Malimbada", district: "Matara" },
  { division: "Matara", district: "Matara" },
  { division: "Mulatiyana", district: "Matara" },
  { division: "Pasgoda", district: "Matara" },
  { division: "Pitabeddara", district: "Matara" },
  { division: "Thihagoda", district: "Matara" },
  { division: "Weligama", district: "Matara" },
  { division: "Welipitiya", district: "Matara" },

  // --- Monaragala District ---
  { division: "Badalkumbura", district: "Monaragala" },
  { division: "Bibile", district: "Monaragala" },
  { division: "Buttala", district: "Monaragala" },
  { division: "Katharagama", district: "Monaragala" },
  { division: "Madulla", district: "Monaragala" },
  { division: "Medagama", district: "Monaragala" },
  { division: "Moneragala", district: "Monaragala" },
  { division: "Sevanagala", district: "Monaragala" },
  { division: "Siyambalanduwa", district: "Monaragala" },
  { division: "Thanamalvila", district: "Monaragala" },
  { division: "Wellawaya", district: "Monaragala" },

  // --- Mullaitivu District ---
  { division: "Manthai East", district: "Mullaitivu" },
  { division: "Maritimepattu", district: "Mullaitivu" },
  { division: "Oddusuddan", district: "Mullaitivu" },
  { division: "Puthukudiyiruppu", district: "Mullaitivu" },
  { division: "Thunukkai", district: "Mullaitivu" },
  { division: "Welioya", district: "Mullaitivu" },

  // --- Nuwara Eliya District ---
  { division: "Ambagamuwa", district: "Nuwara Eliya" },
  { division: "Hanguranketha", district: "Nuwara Eliya" },
  { division: "Kothmale", district: "Nuwara Eliya" },
  { division: "Nuwara Eliya", district: "Nuwara Eliya" },
  { division: "Walapane", district: "Nuwara Eliya" },

  // --- Polonnaruwa District ---
  { division: "Dimbulagala", district: "Polonnaruwa" },
  { division: "Elahera", district: "Polonnaruwa" },
  { division: "Hingurakgoda", district: "Polonnaruwa" },
  { division: "Lankapura", district: "Polonnaruwa" },
  { division: "Medirigiriya", district: "Polonnaruwa" },
  { division: "Thamankaduwa", district: "Polonnaruwa" },
  { division: "Welikanda", district: "Polonnaruwa" },

  // --- Puttalam District ---
  { division: "Anamaduwa", district: "Puttalam" },
  { division: "Arachchikattuwa", district: "Puttalam" },
  { division: "Chilaw", district: "Puttalam" },
  { division: "Dankotuwa", district: "Puttalam" },
  { division: "Kalpitiya", district: "Puttalam" },
  { division: "Karuwalagaswewa", district: "Puttalam" },
  { division: "Madampe", district: "Puttalam" },
  { division: "Mahakumbukkadawala", district: "Puttalam" },
  { division: "Mahawewa", district: "Puttalam" },
  { division: "Mundel", district: "Puttalam" },
  { division: "Nattandiya", district: "Puttalam" },
  { division: "Nawagattegama", district: "Puttalam" },
  { division: "Pallama", district: "Puttalam" },
  { division: "Puttalam", district: "Puttalam" },
  { division: "Vanathavilluwa", district: "Puttalam" },
  { division: "Wennappuwa", district: "Puttalam" },

  // --- Ratnapura District ---
  { division: "Ayagama", district: "Ratnapura" },
  { division: "Balangoda", district: "Ratnapura" },
  { division: "Eheliyagoda", district: "Ratnapura" },
  { division: "Elapatha", district: "Ratnapura" },
  { division: "Godakawela", district: "Ratnapura" },
  { division: "Imbulpe", district: "Ratnapura" },
  { division: "Kahawatta", district: "Ratnapura" },
  { division: "Kalawana", district: "Ratnapura" },
  { division: "Kuruwita", district: "Ratnapura" },
  { division: "Nivithigala", district: "Ratnapura" },
  { division: "Opanayaka", district: "Ratnapura" },
  { division: "Pelmadulla", district: "Ratnapura" },
  { division: "Ratnapura", district: "Ratnapura" },
  { division: "Weligepola", district: "Ratnapura" },

  // --- Trincomalee District ---
  { division: "Gomarankadawala", district: "Trincomalee" },
  { division: "Kantalai", district: "Trincomalee" },
  { division: "Kinniya", district: "Trincomalee" },
  { division: "Kuchchaveli", district: "Trincomalee" },
  { division: "Morawewa", district: "Trincomalee" },
  { division: "Muttur", district: "Trincomalee" },
  { division: "Padavi Sri Pura", district: "Trincomalee" },
  { division: "Seruvila", district: "Trincomalee" },
  { division: "Thambalagamuwa", district: "Trincomalee" },
  { division: "Trincomalee Town and Gravets", district: "Trincomalee" },
  { division: "Verugal", district: "Trincomalee" },

  // --- Vavuniya District ---
  { division: "Vavuniya", district: "Vavuniya" },
  { division: "Vavuniya North", district: "Vavuniya" },
  { division: "Vavuniya South", district: "Vavuniya" },
  { division: "Vengalacheddikulam", district: "Vavuniya" }
];