const NOTIFICATION_SCOPES = {
  UNICAST: 'UNICAST',
  MULTICAST: 'MULTICAST',
  BROADCAST: 'BROADCAST'
};

const RECIPIENT_ROLES = {
  TOURIST: 'TOURIST',
  DRIVER: 'DRIVER',
  GUIDE: 'GUIDE',
  ADMIN: 'ADMIN',
  ALL: 'ALL'
};

const NOTIFICATION_CATEGORIES = {
  BID: 'BID',
  BOOKING: 'BOOKING',
  SAFETY: 'SAFETY',
  PAYMENT: 'PAYMENT',
  ACCOUNT: 'ACCOUNT',
  REVIEW: 'REVIEW',
  INQUIRY: 'INQUIRY',
  BUDGET: 'BUDGET',
  SYSTEM: 'SYSTEM'
};

const NOTIFICATION_PRIORITIES = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
};

const ENTITY_TYPES = {
  BID: 'Bid',
  BOOKING: 'Booking',
  SECURITY_ALERT: 'SecurityAlert',
  PAYMENT: 'Payment'
};

module.exports = {
  NOTIFICATION_SCOPES,
  RECIPIENT_ROLES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_PRIORITIES,
  ENTITY_TYPES
};